//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel
    {
        public decimal channel_id { get; set; }
        public string channel_name { get; set; }
        public string channel_type { get; set; }
    }
}
