//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public decimal driver_id { get; set; }
        public string driver_modal { get; set; }
        public string driver_type { get; set; }
        public Nullable<double> current_latitude { get; set; }
        public Nullable<double> current_longitude { get; set; }
        public Nullable<short> driver_rating { get; set; }
        public Nullable<short> current_orders { get; set; }
    }
}
