//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class hub
    {
        public decimal hub_id { get; set; }
        public string hub_name { get; set; }
        public string hub_city { get; set; }
        public string hub_state { get; set; }
        public Nullable<double> hub_latitude { get; set; }
        public Nullable<double> hub_longitude { get; set; }
    }
}
