//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public decimal payment_id { get; set; }
        public Nullable<decimal> payment_order_id { get; set; }
        public Nullable<double> payment_amount { get; set; }
        public string payment_fee { get; set; }
        public string payment_method { get; set; }
        public string payment_status { get; set; }
    }
}
