//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public decimal store_id { get; set; }
        public Nullable<decimal> hub_id { get; set; }
        public string store_name { get; set; }
        public string store_segment { get; set; }
        public string store_plan_price { get; set; }
        public string store_latitude { get; set; }
        public string store_longitude { get; set; }
    }
}
